build:
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-main
checks:
    php: true
filter: {  }
coding_style:
    php:
        spaces:
            around_operators:
                concatenation: true
