#! usr/bin/env php
<?php

namespace Structural\Adapter;

require_once 'vendor/autoload.php';

$registry = new Registry();

$registry->setFirst('FirstValue');
$registry->setSecond('3.14');

printf("%s \n", $registry->getFirst());
printf("%s \n", $registry->getSecond());

$adapter = new RegistryAdapter(new AnotherRegistry());

$adapter->setFirst('FirstValue');
$adapter->setSecond('3.14');

printf("%s \n", $adapter->getFirst());
printf("%s \n", $adapter->getSecond());
